-- 现网库迁移：devices 表在 tof4 后新增里程与回差字段
ALTER TABLE devices
  ADD COLUMN hr INT(11) NOT NULL DEFAULT 100 COMMENT '湿度里程' AFTER tof4,
  ADD COLUMN nr INT(11) NOT NULL DEFAULT 100 COMMENT '氨气里程' AFTER hr,
  ADD COLUMN tb INT(11) NOT NULL DEFAULT 10 COMMENT '温度回差' AFTER nr,
  ADD COLUMN hb INT(11) NOT NULL DEFAULT 1 COMMENT '湿度回差' AFTER tb,
  ADD COLUMN nb INT(11) NOT NULL DEFAULT 1 COMMENT '氨气回差' AFTER hb;
